<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ThrowbackLauncher</AssemblyName>
    <RootNamespace>RewindLauncher</RootNamespace>
    <ApplicationIcon>Assets\throwback.ico</ApplicationIcon>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\hero.png" LogicalName="ThrowbackLauncher.hero.png" />
    <EmbeddedResource Include="Assets\throwback-logo.png" LogicalName="ThrowbackLauncher.logo.png" />
    <EmbeddedResource Include="Assets\throwback.ico" LogicalName="ThrowbackLauncher.icon.ico" />
  </ItemGroup>
</Project>
